server {
    listen 80;
    listen [::]:80;

    server_name currency.ameta-fin.ru;

    root /var/www/currency.ameta-fin.ru;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
